### ISSUE TITLE
Nested Boolean searches

### ISSUE THREAD

**Issue by chartgerink** [ContentMine/getpapers#15]
Hi,

I am trying to do nested Boolean searches, but I immediately receive an error that an operator was unexpected. More specifically, it is the operator that combines the two Boolean searches that proves to create an error. These kind of searches do work in EuropePMC directly, btw. 

The search I used is `getpapers --query '(TITLE: "QRP" AND TITLE:"misconduct") OR (PUB_TYPE:"retraction of publication")' --outdir test`, see also the attached image.

If I remove the Boolean part from `OR` onward I also receive an error, so it seems that the parentheses might also be the cause of the problem. Any help on why this creates an error and whether this is solvable?

Kind regards,
Chris Hartgerink
![nested boolean](https://cloud.githubusercontent.com/assets/2946344/7587563/8702765a-f8b7-11e4-8224-96b82ff25fb7.png)

**Comment by Blahah** [comment]
The query you quoted above doesn't work for me because of the space between `TITLE:` and  `"QRP"`. However, in the screenshot you don't have the space, so I guess that's not the problem.

If I run the command without the space it works for me
```bash
$ getpapers --query '(TITLE:"QRP" AND TITLE:"misconduct") OR (PUB_TYPE:"retraction of publication")' --outdir test
info: Found 1027600 open access results;
```

(I killed it at that point because I don't want to download 1 million papers :))

This could be a Windows-specific problem. It might be something to do with the way Windows CMD is parsing the command - it might be interpreting the brackets. Could you try:

```getpapers --query '\(TITLE:"QRP" AND TITLE:"misconduct"\) OR \(PUB_TYPE:"retraction of publication"\)' --outdir test```

Unfortunately I don't have a Windows machine to test on.

**Comment by chartgerink** [comment]
I tried as recommended and it does not work, because I get the same error. It seems like a windows specific error. I tried running just `getpapers –query ‘(“QRP”)’ –outdir test` but that gives me an error (also when including the escape `\`). I also tried running it in PowerShell, but equivalent results.

 

Should the OS make a difference outside of the parsing? (I figure not, but I am not familiar with node.js nor am I that experienced in programming, just scripting)

**Comment by Blahah** [comment]
The OS should make no difference to the running of the code. Although I haven't tested on Windows, I have used cross-platform code throughout (I think).

According to [this guide to Windows shell escaping](http://ss64.com/nt/syntax-esc.html), brackets are safe only inside double-quotes. So maybe you need to put double-quotes around the whole command, instead of singles:

```
getpapers --query "(TITLE:\"QRP\" AND TITLE:\"misconduct\") OR (PUB_TYPE:\"retraction of publication\")' --outdir test
```

or the easier to type:

```
getpapers --query "(TITLE:'QRP' AND TITLE:'misconduct') OR (PUB_TYPE:'retraction of publication')' --outdir test
```

**Comment by chartgerink** [comment]
Oh yes! This works :) Thank you.

**Comment by Blahah** [comment]
No problem -  which version worked? Or did both?

I will add a note to the README so future Windows users don't get caught.

**Comment by chartgerink** [comment]
Both worked. My apologies for not specifying.

**Comment by Blahah** [comment]
Great, thanks!
