### ISSUE TITLE
Running getpapers produces nothing, not even with --help

### ISSUE THREAD

**Issue by mw55309** [ContentMine/getpapers#164]
I am on Ubuntu

```sh
sudo apt-get install node
sudo apt-get install npm
sudo npm install --global getpapers
```

All of the above finish without errors.  Then:

```sh
getpapers
```

Nothing

```sh
getpapers --help
```

Nothing

What's happening?

**Comment by blahah** [comment]
@mw55309 the problem is ubuntu's node installation creates all kinds of path and permissions mess. For any node tool, I recommend starting with a userspace node version manager. You should basically never need sudo for node things.

To clean up the mess you might want to:

```bash
sudo apt-get -y remove node npm
```

Then install [`nvm`](https://github.com/creationix/nvm#installation) in user space:

```bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
```

Open a new shell session, or `source ~/.bash_profile`, then install the latest long-term-supported `node` version and `getpapers`:

```bash
nvm install --lts
npm install --global getpapers
getpapers --help
```

**Comment by mw55309** [comment]
Awesome this worked :-)

**Comment by blahah** [comment]
great! just made this so we can link to it from every node command-line tool, and avoid this in the future: https://github.com/blahah/installing-node-tools
