### ISSUE TITLE
arxiv: q-bio not recognised as a distinct subject class

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#37]
```
$getpapers -q 'dinosaurs' --api arxiv -p  --outdir ./car
# it all worked but ...
$ cd car
$ ls
0704.1912v4  1302.3267v1  arxiv_results.json  cond-mat
1209.5439v1  1302.5142v1  astro-ph            hep-ph
```

The subfolders by subject class is cool e.g. astro-ph, hep-ph & cond-mat
... but it looks like q-bio isn't similarly recognised!
http://arxiv.org/abs/1209.5439   1209.5439v1 should be in a q-bio folder, following that convention

**Comment by Blahah** [comment]
The arrangement of the files output from arxiv mode is defined by the article identifiers. If the article is put in a sub-folder (e.g. `astro-ph`) it's because the ArXiv identifier of the preprint started with `astro-ph/`. Only a subset of ArXiv papers have identifiers like this, while most are just a plain identifier like `1209.5439v1`, so most papers end up with no subject-specific subdirectory.

Therefore, I don't think this is a bug, it just reflects the historical changes to the ArXiv ID system.
